### ISSUE TITLE
 Found 0 artifacts.

### ISSUE THREAD

**Issue by jedie** [Robpol86/appveyor_artifacts#4]
I try to use your project here: https://github.com/jedie/pathlib_revised

output on appveyor is:
`Packaging artifacts...OK`
-> https://ci.appveyor.com/project/jedie/pathlib-revised/build/14/job/x6tvlubsb3oos1ew#L170

output on travis is:

```
Build successful. Found 2 jobs.
...
Found 0 artifacts.
```

https://travis-ci.org/jedie/pathlib_revised/jobs/107894365#L433-L45

any idea?

**Comment by Robpol86** [comment]
You don't have any artifacts configured in your appveyor config.
https://ci.appveyor.com/project/jedie/pathlib-revised/build/14/job/x6tvlubsb3oos1ew/artifacts

**Comment by jedie** [comment]
I have used your example from https://github.com/Robpol86/appveyor-artifacts#example in my configs:

https://github.com/jedie/pathlib_revised/blob/master/.travis.yml
https://github.com/jedie/pathlib_revised/blob/master/appveyor.yml

**Comment by Robpol86** [comment]
AppVeyor didn't upload any artifacts according to https://ci.appveyor.com/project/jedie/pathlib-revised/build/14/job/x6tvlubsb3oos1ew/artifacts

You can see that appveyor displays artifacts for one of my projects: https://ci.appveyor.com/project/Robpol86/colorclass/build/1.0.535/artifacts

Can you try again?

**Comment by jedie** [comment]
Must i change something here:

![screenshot](https://snag.gy/aBA6R2.jpg)
