### ISSUE TITLE
Quickstart instructions didn't work for me

### ISSUE THREAD

**Issue by peterbrittain** [Robpol86/appveyor_artifacts#5]
Thanks for writing this tool.  It made the cross-platform, combined coverage for my project a lot easier.

Just one quick observation.  Your quickstart instructions didn't work for me until I explicitly included all coverage files that this tool downloaded.  In short I had to glob all occurrences of `.coverage` to get it to work.  For example I had to use this:

.. code:: yaml

```
after_success:
  - mv .coverage .coverage.travis
  - appveyor-artifacts -m download
  - coverage combine .coverage.travis */.coverage
  - coveralls
```

**Comment by Robpol86** [comment]
Thanks!

Yep, those instructions are more for showing off how to use the tool. The instructions work out of the box for projects that run single tests per commit (one version of Python, or using Tox, etc). For more complex test setups like using matrices or multiple versions of Python You'll need to modify the commands as you've found out.

**Comment by peterbrittain** [comment]
Makes sense.  Feel free to close this issue and/or update yor docs as you wish...
